package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	pkgs, err := loadPackages(context.Background())
	if err != nil {
		log.Fatal(err)
	}
	for _, pkg := range pkgs {
		if err := processPackage(pkg); err != nil {
			fmt.Printf("Warning: %s: %v\n", pkg.Name, err)
		}
	}
}

func loadPackages(ctx context.Context) ([]*packages.Package, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles |
			packages.NeedImports | packages.NeedSyntax |
			packages.NeedTypes | packages.NeedTypesInfo,
		Context: ctx,
		Dir:     ".",
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return nil, err
	}

	var sourcePkgs []*packages.Package
	for _, pkg := range pkgs {
		if isSourcePackage(pkg) {
			sourcePkgs = append(sourcePkgs, pkg)
		}
	}
	return sourcePkgs, nil
}

func isSourcePackage(pkg *packages.Package) bool {
	if pkg.Errors != nil {
		return false
	}
	if strings.HasPrefix(pkg.PkgPath, "_test") {
		return false
	}
	if len(pkg.Syntax) == 0 {
		return false
	}
	return true
}

func processPackage(pkg *packages.Package) error {
	var resetStructs []string

	for _, file := range pkg.Syntax {

		ast.Inspect(file, func(node ast.Node) bool {
			if gen, ok := node.(*ast.GenDecl); ok && gen.Tok == token.TYPE {
				for _, spec := range gen.Specs {
					if ts, ok := spec.(*ast.TypeSpec); ok {
						if _, isStruct := ts.Type.(*ast.StructType); isStruct {
							if hasResetComment(gen.Doc, ts.Doc) {
								resetStructs = append(resetStructs, ts.Name.Name)
							}
						}
					}
				}
			}
			return true
		})
	}

	if len(resetStructs) == 0 {

		return nil
	}

	return generateResetFile(pkg, resetStructs)
}

func hasResetComment(genDoc, specDoc *ast.CommentGroup) bool {
	for _, doc := range []*ast.CommentGroup{genDoc, specDoc} {
		if doc != nil {
			for _, cg := range doc.List {
				if strings.Contains(cg.Text, "// generate:reset") {

					return true
				}
			}
		}
	}
	return false
}

func generateResetFile(pkg *packages.Package, structNames []string) error {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by cmd/reset. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg.Name)

	for _, structName := range structNames {
		code, err := generateResetMethod(pkg, structName)
		if err != nil {
			fmt.Printf("Warning: skip %s.%s: %v\n", pkg.Name, structName, err)
			continue
		}
		buf.WriteString(code)
	}

	outputPath := filepath.Join(filepath.Dir(pkg.GoFiles[0]), "reset.gen.go")
	formatted, err := formatted(buf.Bytes())
	if err != nil {
		return err
	}
	return writeFile(outputPath, formatted)
}

func formatted(data []byte) ([]byte, error) {
	return format.Source(data)
}

func writeFile(path string, data []byte) error {
	return os.WriteFile(path, data, 0666)
}

func generateResetMethod(pkg *packages.Package, structName string) (string, error) {

	structType, err := extractStructType(pkg, structName)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	buf.WriteString(generateMethodSignature(structName))
	buf.WriteString(generateFieldResets(structType))

	return buf.String(), nil
}

func extractStructType(pkg *packages.Package, structName string) (*types.Struct, error) {

	var structObj types.Object
	for ident, obj := range pkg.TypesInfo.Defs {
		if ident != nil && ident.Name == structName && obj != nil {
			structObj = obj
			break
		}
	}

	if structObj == nil {
		return nil, errors.New("struct not found: " + structName)
	}

	typeName, ok := structObj.(*types.TypeName)
	if !ok {
		return nil, errors.New("not TypeName: " + structName)
	}

	named, ok := typeName.Type().(*types.Named)
	if !ok {
		return nil, errors.New("not Named type: " + structName)
	}

	var structType *types.Struct
	underlying := named.Underlying()
	if ptr, ok := underlying.(*types.Pointer); ok {
		structType = ptr.Elem().Underlying().(*types.Struct)
	} else {
		structType = underlying.Underlying().(*types.Struct)
	}
	return structType, nil
}

func generateMethodSignature(structName string) string {
	return fmt.Sprintf("// %s resets %s to zero values.\nfunc (r *%s) Reset() {\n\tif r == nil {\n\t\treturn\n\t}\n",
		structName, structName, structName)
}

func generateFieldResets(structType *types.Struct) string {
	var buf bytes.Buffer

	for i := 0; i < structType.NumFields(); i++ {
		field := structType.Field(i)
		fieldName := field.Name()
		fmt.Fprintf(&buf, "\n\t// %s (%s)\n", fieldName, field.Type())

		typ := field.Type().Underlying()
		switch t := typ.(type) {
		case *types.Basic:
			buf.WriteString(basicReset(fieldName, t))
		case *types.Slice:
			fmt.Fprintf(&buf, "\tr.%s = r.%s[:0]\n", fieldName, fieldName)
		case *types.Map:
			fmt.Fprintf(&buf, "\tclear(r.%s)\n", fieldName)
		case *types.Pointer:
			buf.WriteString(pointerReset(fieldName, t.Elem()))
		case *types.Named:
			buf.WriteString(namedReset(fieldName, t))
		default:
			fmt.Fprintf(&buf, "\t// TODO: r.%s (%T)\n", fieldName, t)
		}
	}

	fmt.Fprintf(&buf, "}\n\n")

	return buf.String()
}

func basicReset(fieldName string, basic *types.Basic) string {
	switch basic.Kind() {
	case types.Bool:
		return fmt.Sprintf("\tr.%s = false\n", fieldName)
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64:
		return fmt.Sprintf("\tr.%s = 0\n", fieldName)
	case types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64:
		return fmt.Sprintf("\tr.%s = 0\n", fieldName)
	case types.Float32, types.Float64:
		return fmt.Sprintf("\tr.%s = 0\n", fieldName)
	case types.String:
		return fmt.Sprintf("\tr.%s = \"\"\n", fieldName)
	default:
		return fmt.Sprintf("\tr.%s = %s\n", fieldName, basic.String())
	}
}

func pointerReset(fieldName string, elem types.Type) string {
	if named, ok := elem.(*types.Named); ok {
		return fmt.Sprintf(`	if r.%s != nil {
		if resetter, ok := r.%s.(interface{Reset()}); ok {
			resetter.Reset()
		} else {
			*r.%s = *new(%s)
		}
	}
`, fieldName, fieldName, fieldName, named.Obj().Name())
	}
	return fmt.Sprintf(`	if r.%s != nil {
		*r.%s = *new(%T)
	}
`, fieldName, fieldName, elem)
}

func namedReset(fieldName string, named *types.Named) string {
	return fmt.Sprintf(`	if resetter, ok := r.%s.(interface{Reset()}); ok {
		resetter.Reset()
	} else {
		r.%s = %s{}
	}
`, fieldName, fieldName, named.Obj().Name())
}
